domain='https://monbot.hopto.org'
apm_id='admin'
apm_pw='New1234!'
apm_url='https://monbot.hopto.org:3000/login'
snapshot_url='https://monbot.hopto.org:3000'

db_host='monbot.hopto.org'
db_user='izyrtm'
db_pw='new1234!'
db_datadbase='monbot'